version: '3.8'

services:
  mdp-client:
    container_name: mdp-client
    restart: unless-stopped
    # set prod image here
    # image: ...
    build:
      # src must be in context
      context: ./client
      dockerfile: docker/Dockerfile
    depends_on:
      - mdp-server
    networks:
      - internal-client
    environment:
      - NODE_ENV=production
    env_file:
      - ./client/.env
    
    # nginx ports
    # either open port or route through traefik
    ports:
      - '3002:80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.mb-client-secure.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.mb-client-secure.entrypoints=websecure'
      - 'traefik.http.routers.mb-client-secure.service=mb-client-svc'
      - 'traefik.http.services.mb-client-svc.loadbalancer.server.port=80'

  mdp-server:
    container_name: mdp-server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    depends_on:
      - mdp-mongo
    ports:
      - '5000'
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env
    networks:
      - default
      - internal-client

  mdp-mongo:
    image: mongo:6.0.3
    container_name: mdp-mongo
    restart: unless-stopped
    ports:
      - '27017'
    env_file:
      - ./server/.env
    volumes:
      - ./server/docker/mongo-data:/data/db
    networks:
      - default

networks:
  default:
    name: mdp-default
  internal-client:
    name: mdp-client
